### ISSUE TITLE
What is the purpose of `IV` / `iv`?

### ISSUE THREAD

**Issue by coolaj86** [mylofi/local-data-lock#5]
My understanding is that IV (initialization vector) is a random salt used in AES to prevents known-text attacks, and is a public value to be appended before or after the encrypted bytes to form the full payload which is then stored or transmitted, etc.

I see the term being used in various places in the code here, none of them match my understanding.

`iv` _looks like_ it's being used as a seed for key expansion.

`IV_BYTES_LENGTH + 2` seem to be expressing the length of the `userHandle`, but not in a way that seems like it's related to an IV as describe above?

Is the naming leftover from some other iteration of the code? Or is it describing some other form of IV that applies to this usage?

**Comment by getify** [comment]
> I see the term being used in various places 

As far as I can tell, there's no relevant difference between an "IV" and a "seed. They're both sets of random bytes that are used in cryptographic operations (like hashing, keypair generation, etc). I've read tons of various sources on such cryptographic topics, and couldn't seem to discover any consistent rule for when "IV" was used and when "Seed" was used. So I just made the decision to simplify and use "iv" in code. And I believe in the docs, I use "IV/seed" to make that indistinction clear.

To be clear, as it relates to the keypair generation, it's being used as a *seed* for deterministic keypair generation.

> IV_BYTES_LENGTH + 2

That specific code is because the IV/seed being used for the keypair generation is what is pushed into the `userHandle`, however... authenticators require passkeys to have unique `userHandle` values. I wanted to be able to let users register multiple passkeys for the same encryption key (IV/seed), so the additional 2 bytes on the end are a counter (0-65535) that increments with each passkey, thereby ensuring the `userHandle` is indeed *unique* per passkey, but multiple passkeys can end up providing the IV/seed for the same keypair.

**Comment by coolaj86** [comment]
I believe the distinction is that IV is a _publishable_ salt value and seed is a _private_ secret value.

For example, in PBKDF the "password" bytes are the "seed" bytes and the "salt" bytes are the "iv" bytes. In AES the key/secret is often the result of PBKDF2 or similar and the iv/salt is generated for each invocation of the sign function.

https://github.com/sodium-friends/sodium-native/blob/b06cb6e496afefdbf527868414cdc34221425595/extensions/pbkdf2/pbkdf2.c#L36-L53

And AES as I described above ^^.

The seed/secret is often derived from some user action, or something the user has (e.g. a password, api key secret) and the iv/salt is completely internal to the process.

IVs are safe to store unencrypted and often be made public because they alone don't carry any information that helps an attacker - aside from perhaps getting a head start on precomputing hashes for a specific user or piece of data, which isn't much of a computational advantage since they still have to either exhaust the keyspace or have access to the database that has the hashes either way.

**Comment by getify** [comment]
OK, that's a reasonable observation to make I guess. But I don't think it matters with respect to this project. I could rename the `iv` field to `seed`, but I think that just creates breakage (if anyone is using existing outputs from this library -- though obviously it's very new)... and it doesn't really make a big change/impact.

I *did* foresee the need to change the lock-key format, which is why it includes versioning. So it *could* be done. But I guess I'd rather not churn for just a nuanced semantic difference.

**Comment by getify** [comment]
closing for now, but we may revisit this at some point if there's future confusions it creates.
